-- Alter text columns (ignore errors if already altered)
DO $$ BEGIN ALTER TABLE schools ALTER COLUMN logo TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE schools ALTER COLUMN motto TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE users ALTER COLUMN avatar TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE students ALTER COLUMN photo TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE teachers ALTER COLUMN photo TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE enrollments ALTER COLUMN photo TYPE text; EXCEPTION WHEN OTHERS THEN END; $$;
