package com.api.educore.model;

public enum ClassLevel {
    PRIMEIRA_CLASSE,
    SEGUNDA_CLASSE,
    TERCEIRA_CLASSE,
    QUARTA_CLASSE,
    QUINTA_CLASSE,
    SEXTA_CLASSE,
    SETIMA_CLASSE,
    OITAVA_CLASSE,
    NONA_CLASSE,
    DECIMA_CLASSE,
    DECIMA_PRIMEIRA_CLASSE,
    DECIMA_SEGUNDA_CLASSE,
    DECIMA_TERCEIRA_CLASSE
}
