package com.api.educore.model;

public enum Permission {
    // Alunos
    VIEW_ALUNO, CREATE_ALUNO, EDIT_ALUNO, DELETE_ALUNO,
    // Professores
    VIEW_PROFESSOR, CREATE_PROFESSOR, EDIT_PROFESSOR, DELETE_PROFESSOR,
    // Turmas
    VIEW_TURMA, CREATE_TURMA, EDIT_TURMA, DELETE_TURMA,
    // Notas
    VIEW_NOTA, EDIT_NOTA, DELETE_NOTA,
    // Assiduidade
    VIEW_ASSIDUIDADE, EDIT_ASSIDUIDADE,
    // Matriculas
    VIEW_MATRICULA, CREATE_MATRICULA, EDIT_MATRICULA, DELETE_MATRICULA,
    // Financeiro
    VIEW_FINANCEIRO, CREATE_FINANCEIRO, EDIT_FINANCEIRO, DELETE_FINANCEIRO,
    // Biblioteca
    VIEW_BIBLIOTECA, CREATE_BIBLIOTECA, EDIT_BIBLIOTECA, DELETE_BIBLIOTECA,
    // Documentos
    VIEW_DOCUMENTO, CREATE_DOCUMENTO, EDIT_DOCUMENTO, DELETE_DOCUMENTO,
    // Transportes
    VIEW_TRANSPORTE, CREATE_TRANSPORTE, EDIT_TRANSPORTE, DELETE_TRANSPORTE,
    // Academic
    VIEW_ACADEMICO, CREATE_ACADEMICO, EDIT_ACADEMICO, DELETE_ACADEMICO,
    // Relatorios
    VIEW_RELATORIO,
    // Configuracoes
    VIEW_CONFIGURACAO, EDIT_CONFIGURACAO,
    // Escolas
    VIEW_ESCOLA, CREATE_ESCOLA, EDIT_ESCOLA, DELETE_ESCOLA,
    // Utilizadores
    VIEW_UTILIZADOR, CREATE_UTILIZADOR, EDIT_UTILIZADOR, DELETE_UTILIZADOR,
    // Permissoes
    VIEW_PERMISSAO, EDIT_PERMISSAO
}
